# Generated by Django 4.2.2 on 2023-07-03 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=150)),
                ('confirmation_number', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('image_url', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('itineraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travelserverapi.itineraryitem')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(null=True)),
                ('phone_number', models.CharField(max_length=100)),
            ],
            bases=('travelserverapi.itineraryitem',),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('itineraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travelserverapi.itineraryitem')),
                ('departure_airport', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_airport', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('layover', models.BooleanField()),
            ],
            bases=('travelserverapi.itineraryitem',),
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('itineraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travelserverapi.itineraryitem')),
                ('phone_number', models.CharField(max_length=100)),
                ('checkin_time', models.TimeField(null=True)),
                ('checkout_time', models.TimeField(null=True)),
            ],
            bases=('travelserverapi.itineraryitem',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('itineraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travelserverapi.itineraryitem')),
                ('note_info', models.TextField()),
            ],
            bases=('travelserverapi.itineraryitem',),
        ),
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('itineraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travelserverapi.itineraryitem')),
                ('phone_number', models.CharField(max_length=100)),
                ('pickup_time', models.TimeField()),
                ('dropoff_time', models.TimeField()),
            ],
            bases=('travelserverapi.itineraryitem',),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelserverapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelserverapi.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelserverapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='SharedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelserverapi.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelserverapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travelserverapi.trip'),
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('itineraryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travelserverapi.itineraryitem')),
                ('departure_station', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_station', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('arrival_station_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival', to='travelserverapi.address')),
                ('departure_station_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure', to='travelserverapi.address')),
                ('itinerary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='travelserverapi.itineraryitem')),
            ],
            bases=('travelserverapi.itineraryitem',),
        ),
        migrations.AddConstraint(
            model_name='sharerequest',
            constraint=models.UniqueConstraint(fields=('user', 'trip'), name='unique_share_request'),
        ),
        migrations.AddConstraint(
            model_name='sharedtrip',
            constraint=models.UniqueConstraint(fields=('user', 'board'), name='unique_share_trip'),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelserverapi.address'),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='itinerary_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalcars', to='travelserverapi.itineraryitem'),
        ),
        migrations.AddField(
            model_name='note',
            name='itinerary_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_here', to='travelserverapi.itineraryitem'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelserverapi.address'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='itinerary_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgings', to='travelserverapi.itineraryitem'),
        ),
        migrations.AddField(
            model_name='flight',
            name='itinerary_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='travelserverapi.itineraryitem'),
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelserverapi.address'),
        ),
        migrations.AddField(
            model_name='event',
            name='itinerary_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='travelserverapi.itineraryitem'),
        ),
    ]
